name: Build & deploy mpf-docs to missionpinball.org

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate project showcase pages from .yaml files
        run: python build_tools/generate_showcase_pages.py

      - name: Build and deploy site
        #run: mkdocs gh-deploy --force
        run: mike deploy 0.57 latest
